version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=tests
    ports:
      - 5430:5432
    restart: always
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data

  # api:
  #   container_name: api
  #   command: bash -c "
  #     yarn prisma generate && yarn prisma migrate dev && yarn dev"
  #   stdin_open: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - PORT=3000
  #   env_file:
  #     - .env
  #   restart: always
  # volumes:
  #   - .:/app
# volumes:
#   postgres-data:
#     driver: local
