version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    container_name: api
    command: bash -c "
      yarn prisma migrate dev
      && yarn dev"
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env

volumes:
  postgres-data:
